### ISSUE TITLE
Errors when using in .NET Core 2.0 project

### ISSUE THREAD

**Issue by Mardaneus86** [lurumad/core-flash#1]
I just tried using this component in a new ASP .NET Core Web App project targeting `.NET Core 2.0` and ran into a few minor problems.

In the _ViewImports.cshtml,`@using Core.Flash.Web` should become `@using Core.Flash.Mvc`. A small adjustment in the Readme.md would be sufficient as a fix.

I also had to register the `HttpContextAccessor` in the Startup class (see https://stackoverflow.com/a/37373557/6192895):
```csharp
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```
Perhaps this can be added in the `UseFlashes()` extension?

**Comment by magiak** [comment]
I had the same problem with the namespace. I can fix the issue and create pull request but lurumad is not active for last few months...

**Comment by lurumad** [comment]
Hi @magiak 

Please, create a PR

**Comment by anisalibegic** [comment]
I'ts not working as there are no flashes shown. But, it works after modifying the tag helper:
```
var alerts = string.Empty;
var messages = tempData.Get<Queue<Message>>(...);

while (messages.Count > 0)
{
    var message = messages.Dequeue();
    alerts += string.Format(HtmlStandardTemplate, message.Type, message.Text);
}

output.Content.SetHtmlContent(alerts);
```

**Comment by lurumad** [comment]
This weekend I'm going to review it and publish a new package.

**Comment by lurumad** [comment]
Hi folks

I've update Core.Flash to 2.0.0 with some changes (not breaking) but I've decided to update the version in order to line up with the versión of .NET Standard 2.0.

Please, try it and close the issue if everything goes well!

Kind regards!

**Comment by anisalibegic** [comment]
I have no problems after updating to 2.0.0.
